---
- name: kind/feature
  color: "a2eeef"
  description: "Categorizes issue or PR as related to a new feature."
  from_name: enhancement # github default
- name: kind/bug
  color: "d73a4a"
  description: "Categorizes issue or PR as related to a bug (i.e. something is not working)."
  from_name: bug # github default
- name: kind/test
  color: "775fcb"
  description: "Categorizes issue or PR addressing tests (missing, adding, problem)."
- name: kind/documentation
  color: "0075ca"
  description: "Categorizes issue or PR as related to documentation."
  from_name: documentation # github default
- name: kind/security
  color: "775fcb"
  description: "Categorizes issue or PR as related to security."
- name: kind/infrastructure
  color: "775fcb"
  description: "Categorizes issue or PR improving development/releases/Continious Integration (CI)."
- name: kind/dependencies
  color: "ededed"
  description: "Categorizes pull requests that update a dependency file."
- name: kind/support
  color: "775fcb"
  description: "Categorizes issues related to questions."

- name: needs-triage
  color: "EDEDED"
  description: "Indicates an issue or PR lacks a `triage/foo` label and requires one."
- name: triage/duplicate
  color: "D455D0"
  description: "Indicates an issue is a duplicate of other open issue."
  from_name: duplicate # github default
- name: triage/needs-information
  color: "D455D0"
  description: "Indicates an issue needs more information in order to work on it."
- name: triage/not-reproducible
  color: "D455D0"
  description: "Indicates an issue can not be reproduced as described."
  from_name: invalid # github default
- name: triage/accepted
  color: "8FC951"
  description: "Indicates an issue or PR is ready to be actively worked on."
- name: triage/wontfix
  color: "ffffff"
  description: This will not be worked on
  from_name: wontfix # github default

- name: good first issue # github default
  color: "7057ff"
  description: "Denotes an issue ready for a new contributor."
- name: help wanted # github default
  color: "008672"
  description: "Denotes an issue that needs help from other contributors."

- name: priority/low
  color: "0000FF"
  description: "Categorizes issues or PRs as low priority."
- name: priority/high
  color: "FF0000"
  description: "Categorizes issues or PRs as high priority."

- name: size/XS
  color: "009900"
  description: "Denotes a PR that changes 0-9 lines, ignoring generated files."
- name: size/S
  color: "77bb00"
  description: "Denotes a PR that changes 10-29 lines, ignoring generated files."
- name: size/M
  color: "eebb00"
  description: "Denotes a PR that changes 30-99 lines, ignoring generated files."
- name: size/L
  color: "ee9900"
  description: "Denotes a PR that changes 100-499 lines, ignoring generated files."
- name: size/XL
  color: "ee5500"
  description: "Denotes a PR that changes 500-999 lines, ignoring generated files."
- name: size/XXL
  color: "ee0000"
  description: "Denotes a PR that changes 1000+ lines, ignoring generated files."
