---
- name: kind/feature
  color: "A2EEEF"
  description: "Categorizes issue or PR as related to a new feature."
  from_name: enhancement # github default
- name: kind/bug
  color: "D73A4A"
  description: "Categorizes issue or PR as related to a bug (i.e. something is not working)."
  from_name: bug # github default
- name: kind/documentation
  color: "0075CA" # same as 'kind/support'
  description: "Categorizes issue or PR as related to documentation."
  from_name: documentation # github default
- name: kind/support
  color: "0075CA"
  description: "Categorizes issues related to questions."
- name: kind/infrastructure
  color: "775FCB"
  description: "Categorizes issue or PR improving development/releases/Continious Integration (CI)."
- name: kind/test
  color: "775FCB" # same as 'kind/infrastructure'
  description: "Categorizes issue or PR addressing tests (missing, adding, problem)."
- name: kind/security
  color: "775FCB" # same as 'kind/infrastructure'
  description: "Categorizes issue or PR as related to security."
- name: kind/dependencies
  color: "EDEDED"
  description: "Categorizes pull requests that update a dependency file."

- name: needs-triage
  color: "EDEDED" # same as 'do-not-merge'
  description: "Indicates an issue or PR lacks a `triage/foo` label and requires one."
- name: triage/duplicate
  color: "D455D0"
  description: "Indicates an issue is a duplicate of other open issue."
  from_name: duplicate # github default
- name: triage/needs-information
  color: "D455D0"
  description: "Indicates an issue needs more information in order to work on it."
- name: triage/not-reproducible
  color: "D455D0"
  description: "Indicates an issue can not be reproduced as described."
  from_name: invalid # github default
- name: triage/accepted
  color: "0E8A16" # githubs' default dark lime green color
  description: "Indicates an issue or PR is ready to be actively worked on."
- name: triage/wontfix
  color: "B60205" # same as 'do-not-merge'
  description: This will not be worked on
  from_name: wontfix # github default

- name: good first issue # github default
  color: "7057FF"
  description: "Denotes an issue ready for a new contributor."
- name: help wanted # github default
  color: "008672"
  description: "Denotes an issue that needs help from other contributors."

- name: priority/low
  color: "C5DEF5" # githubs' default light grayish blue
  description: "Categorizes issues or PRs as low priority."
- name: priority/high
  color: "FF0000"
  description: "Categorizes issues or PRs as high priority."

- name: size/XS
  color: "C5DEF5" # same as 'priority/low'
  description: "Denotes a PR that changes 0-9 lines, ignoring generated files."
- name: size/S
  color: "C5DEF5" # same as 'priority/low'
  description: "Denotes a PR that changes 10-29 lines, ignoring generated files."
- name: size/M
  color: "EEBB00"
  description: "Denotes a PR that changes 30-99 lines, ignoring generated files."
- name: size/L
  color: "EE9900"
  description: "Denotes a PR that changes 100-499 lines, ignoring generated files."
- name: size/XL
  color: "EE5500"
  description: "Denotes a PR that changes 500-999 lines, ignoring generated files."
- name: size/XXL
  color: "EE0000"
  description: "Denotes a PR that changes 1000+ lines, ignoring generated files."

- name: do-not-merge
  color: "B60205" # githubs' default strong red color
  description: "Indicates that a PR should not merge."
- name: do-not-merge/work-in-progress
  color: "B60205" # githubs' default strong red color
  description: "Indicates that a PR should not merge because it is a work in progress."
- name: do-not-merge/needs-rebase
  color: "B60205" # githubs' default strong red color
  description: "Indicates a PR cannot be merged because it has merge conflicts with HEAD."
- name: lgtm
  color: "0E8A16" # githubs' default strong green color
  description: " Indicates that a PR is ready to be merged."

# https://docs.renovatebot.com/configuration-options/#rebaselabel
- name: renovate/rebase
  color: "00A9BF" # renovate logo background color
  description: "Manually request Renovate to recreate/rebase the PR by adding this label."
# https://docs.renovatebot.com/configuration-options/#stopupdatinglabel
- name: renovate/stop-updating
  color: "00A9BF" # renovate logo background color
  description: "Manually request Renovate to stop updating a PR by adding this label."
