---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for a list of all hooks
repos:
  ### GENERAL ###
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-json
        exclude: ".devcontainer/devcontainer.json"
      - id: check-toml
      - id: check-xml
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: &generated_pages_exclude | # sync with .prettierignore!
          (?x)^(
            README.md|
            SECURITY.md
          )$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: |
          (?x)^(
              .cruft.json|
          )$

  # opinionated code formatter for all things frontend (also includes Markdown, JSON, YAML)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  ### PYTHON ###
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: [] # as per requirements.txt

  # the uncompromising (opinionated / barely configurable) PEP8 Python code formatter.
  - repo: https://github.com/psf/black
    rev: "24.10.0"
    hooks:
      - id: black

  # isort alternative
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus, --add-import, "from __future__ import annotations"]

  # formats docstrings to follow PEP 257.
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place]

  # flake8 is a python tool that glues together…
  #   pycodestyle (befriended with `black` through config changes),
  #   pyflakes (detects various error by parsing [not importing] source file's),
  #   mccabe (https://en.wikipedia.org/wiki/Cyclomatic_complexity checker) and
  #   some third-party plugins
  # …to check the style and quality of python code.
  - repo: https://github.com/pycqa/flake8
    rev: "7.1.1"
    hooks:
      - id: flake8

default_language_version:
  python: python3
ci:
  autoupdate_schedule: quarterly
  autofix_commit_msg: |
    chore(pre-commit): auto fixes from hooks :rotating_light:

    for more information, see https://pre-commit.ci
  autoupdate_commit_msg: |
    chore(pre-commit): autoupdate :arrow_up:

    TIP: you can trigger a re-run on a pull request by commenting `pre-commit.ci run` (must appear on a line by itself)
exclude: ".idea"
