= ansible-role-goaccess
Jonas Pammer <opensource@jonaspammer.at>;
:toc:
:toclevels: 2
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Very Relevant Status Badges
https://github.com/JonasPammer/ansible-role-goaccess/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-goaccess/actions/workflows/ci.yml/badge.svg[Testing CI]]


An Ansible role for installing GoAccess, a real-time web log analyzer that runs in a terminal or the browser.


toc::[]

[[meta]]
== 🔎 Metadata
Below you can find information on…

* the role's required Ansible version
* the role's supported platforms
* the role's https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-dependencies[role dependencies]

.link:meta/main.yml[]
[source,yaml]
----
include::meta/main.yml[]
----


[[requirements]]
== 📌 Requirements
// Any prerequisites that may not be covered by this role or Ansible itself should be mentioned here.
The Ansible User needs to be able to `become`.


The https://galaxy.ansible.com/community/general[`community.general` collection]
must be installed on the Ansible controller.


[[variables]]
== 📜 Role Variables
// A description of the settable variables for this role should go here
// and any variables that can/should be set via parameters to the role.
// Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.)
// should be mentioned here as well.

[source,yaml]
----
goaccess_dependency_packages: [OS-dependant by default, see /defaults directory]
----
List of packages to install from the system's package manager.
See https://github.com/allinurl/goaccess#distribution-packages[GoAccess Official Documentation] for reference.

[source,yaml]
----
goaccess_install_method: "source"
----
One of "`source`" or "`system`".

[[variables::used_by_system_method]]
=== Role Variables used by the `system`-installation-method

[source,yaml]
----
goaccess_system_install_official_repo: true
----
(Debian/Ubuntu only)
Wheter to install https://goaccess.io/download#official-repo[
GoAccess's Official APT Repository].
This is used to get a more recent version than the one packaged in the system itself.

[source,yaml]
----
goaccess_system_package_state: present
----
When using `goaccess_system_install_official_repo`
you can change this to "`latest`" to ensure that
this role installs the latest available `goaccess` from the system repository.

[[variables::used_by_source_method]]
=== Role Variables used by the `source`-installation-method

[source,yaml]
----
goaccess_source_version: "v{{ goaccess_version }}"
----
The https://github.com/allinurl/goaccess/tags[git version] to download.

[source,yaml]
----
goaccess_version: 1.6
----
The goaccess version string to check against.

[source,yaml]
----
goaccess_source_dependency_packages: [OS-dependant by default, see /defaults directory]
----
List of packages to install from the system's package manager.

[source,yaml]
----
goaccess_source_configure_parameters: "--enable-utf8 --enable-geopip=mmdb"
----
Build Configuration Arguments to pass to `./configure` (autoconf)
which creates the `Makefile` and `src/config.h` (and others).

The Default Options result in the following summary:
----
  Prefix         : /usr/local
  Package        : goaccess
  Version        : 1.6
  Compiler flags :  -pthread
  Linker flags   : -lnsl -lncursesw -lmaxminddb -lpthread
  UTF-8 support  : yes
  Dynamic buffer : no
  Geolocation    : GeoIP2
  Storage method : In-Memory with On-Disk Persistent Storage
  TLS/SSL        : no
  Bugs           : hello@goaccess.io
----

[TIP]
These options are also displayed when executing `goaccess --version`.


=== Role Variables for creating a GoAccess Configuration File

[source,yaml]
----
goaccess_conf_file_dir: "/etc"
goaccess_conf_file_owner: root
goaccess_conf_file_group: root
goaccess_conf_file_mode: u=rw,g=r,o=
----
Location of the `.goaccess` file to generate.
https://goaccess.io/man#options[Can be] in the home directory of a user.

[source,yaml]
----
## Time Format Options (required) ##
goaccess_conf_time_format: "%H:%M:%S" # (Default used by Apache/NGINX's log format Added by role-author)

## Date Format Options (required) ##
goaccess_conf_date_format: "%d/%b/%Y" # (Default used by Apache/NGINX's log format Added by role-author)

## Log Format Options (required) ##
goaccess_conf_log_format: COMMON # (Default Added by role-author)

## UI Options ##
goaccess_conf_color_scheme: 2 # (Default Added by role-author)
goaccess_conf_config_dialog: false
goaccess_conf_hl_header: true
goaccess_conf_html_custom_css: ~
goaccess_conf_html_custom_js: ~
goaccess_conf_html_prefs: ~
goaccess_conf_html_report_title: ~
goaccess_conf_json_pretty_print: true # (Default Changed by role-author)
goaccess_conf_no_color: false
goaccess_conf_no_column_names: false
goaccess_conf_no_csv_summary: false
goaccess_conf_no_progress: false
goaccess_conf_no_tabScroll: false
goaccess_conf_no_parsing_spinner: ~
goaccess_conf_no_html_last_updated: ~
goaccess_conf_with_mouse: true # (Default Changed by role-author)
goaccess_conf_max_items: ~
goaccess_COLOR_: []
# - "HITS color110:color-1"
# - …

## Server Options ##
goaccess_conf_addr: ~
goaccess_conf_daemonize: ~
goaccess_conf_origin: ~
goaccess_conf_port: ~
goaccess_conf_pid_file: ~
goaccess_conf_real_time_html: ~
goaccess_conf_ssl_cert: ~
goaccess_conf_ssl_key: ~
goaccess_conf_ws_url: ~
goaccess_conf_fifo_in: ~
goaccess_conf_fifo_out: ~

## File Options ##
goaccess_conf_log_file: "/var/log/apache2/access.log"
goaccess_conf_debug_file: ~
goaccess_conf_config_file: ~
goaccess_conf_invalid_requests: ~
goaccess_conf_no_global_config: ~

## Parser Options ##
goaccess_conf_agentList: true # (Default Changed by role-author)
goaccess_conf_with_output_resolver: true # (Default Changed by role-author)
goaccess_conf_exclude_ip: []
goaccess_conf_http_method: true
goaccess_conf_http_protocol: true
goaccess_conf_output: ~
goaccess_conf_no_query_string: fals
goaccess_conf_no_term_resolver: false
goaccess_conf_444_as_404: false
goaccess_conf_4xx_to_unique_count: false
goaccess_conf_anonymize_ip: ~
goaccess_conf_all_static_files: false
goaccess_conf_browsers_file: ~
goaccess_conf_date_spec: ~
goaccess_conf_double_decode: false
goaccess_conf_enable_panel: []
goaccess_conf_hide_referer: []
goaccess_conf_hour_spec: ~
goaccess_conf_ignore_crawlers: false
goaccess_conf_crawlers_only: false
goaccess_conf_ignore_statics: ~
goaccess_conf_ignore_panel: []
goaccess_conf_ignore_referer: []
goaccess_conf_ignore_status: []
goaccess_conf_keep_last: ~
goaccess_conf_no_ip_validation: ~
goaccess_conf_num_tests: ~
goaccess_conf_process_and_exit: ~
goaccess_conf_real_os: true
goaccess_conf_sort_panel: []
goaccess_conf_static_file:
  - .css
  - .js
  - .jpg
  - .png
  - .gif
  - .ico
  - .jpeg
  - .pdf
  - .csv
  - .mpeg
  - .mpg
  - .swf
  - .woff
  - .woff2
  - .xls
  - .xlsx
  - .doc
  - .docx
  - .ppt
  - .pptx
  - .txt
  - .zip
  - .ogg
  - .mp3
  - .mp4
  - .exe
  - .iso
  - .gz
  - .rar
  - .svg
  - .bmp
  - .tar
  - .tgz
  - .tiff
  - .tif
  - .ttf
  - .flv
  - .dmg
  - .xz
  - .zst # (▲ GoAccess Default)
  - .avi # (▼ Added by role-author)
  - .bz2
  - .jar
  - .ogv
  - .webm
  - .mkv
  - .ods
  - .odt
  - .wav
  - .webp

## GeoIP Options ##
goaccess_conf_std_geopip: ~
goaccess_conf_geoip_database: ~

## Persistence Options ##
goaccess_conf_db_path: ~
goaccess_conf_persist: ~
goaccess_conf_restore: ~
----
Configuration Options used in goaccess' configuration file template.
Consult https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf[
the official GoAccess Git Repository under "config/goaccess.conf"]
for detailed comments of each variable.

Normal-Properties with value of `None` (`~`) as well as Array-Properties with size of 0 (`[]`)
will not be inserted-into/used-in the Template.


// TODO maybe even add tasks that download geoip2 database if goaccess_conf_geoip-database was given or something like that?


==== Role Variables for creating a systemd service

This service only works if you've correctly filled-in
GoAccess's Configuration File so it starts without error or interuption
when called with `--real-time-html`.

[source,yaml]
----
goaccess_systemd: false
----
Toggle this feature.

[source,yaml]
----
goaccess_conf_file_owner: root
goaccess_conf_file_group: root
goaccess_conf_file_mode: u=rw,g=r,o=
----
Systemd Unit and File Permissions Options.

[source,yaml]
----
goaccess_systemd_name: "goaccess-{{ goaccess_conf_file_owner }}"
goaccess_systemd_description: "Service that generates real-time HTML reports of GoAccess using configuration in {{ goaccess_conf_file_dir }}"
----
Systemd Unit Options.

[source,yaml]
----
goaccess_systemd_html_output_location: "/var/www/html/goaccess.html"
----
Path passed to `goaccess --real-time-html`


[[public_vars]]
== 📜 Facts/Variables defined by this role

Each variable listed in this section
is dynamically defined when executing this role (and can only be overwritten using `ansible.builtin.set_facts`) _and_
is meant to be used not just internally.


[[dependencies]]
== 👫 Dependencies
// A list of other roles should go here,
// plus any details in regard to parameters that may need to be set for other roles,
// or variables that are used from other roles.



[[example_playbooks]]
== 📚 Example Playbook Usages
// Including examples of how to use this role in a playbook for common scenarios is always nice for users.

[NOTE]
====
This role is part of https://github.com/JonasPammer/ansible-roles[
many compatible purpose-specific roles of mine].

The machine needs to be prepared.
In CI, this is done in `molecule/resources/prepare.yml`
which sources its soft dependencies from `requirements.yml`:

.link:molecule/resources/prepare.yml[]
[source,yaml]
----
include::molecule/resources/prepare.yml[]
----

The following diagram is a compilation of the "soft dependencies" of this role
as well as the recursive tree of their soft dependencies.

image:https://raw.githubusercontent.com/JonasPammer/ansible-roles/master/graphs/dependencies_goaccess.svg[
requirements.yml dependency graph of jonaspammer.goaccess]
====

.Minimum Viable Play
====
[source,yaml]
----
roles:
  - "jonaspammer.goaccess"

vars:
  some_var: "some_value"
----
====


[[development]]
== 📝 Development
// Badges about Conventions in this Project
https://conventionalcommits.org[image:https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg[Conventional Commits]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-goaccess/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-goaccess/master.svg[pre-commit.ci status]]
// image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]

include::DEVELOPMENT.adoc[]


[[contributing]]
== 💪 Contributing
image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome]
https://open.vscode.dev/JonasPammer/ansible-role-goaccess[image:https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc[Open in Visual Studio Code]]

include::CONTRIBUTING.adoc[]


[[changelog]]
== 🗒 Changelog
Please refer to the
https://github.com/JonasPammer/ansible-role-goaccess/releases[Release Page of this Repository]
for a human changelog of the corresponding
https://github.com/JonasPammer/ansible-role-goaccess/tags[Tags (Versions) of this Project].

Note that this Project adheres to Semantic Versioning.
Please report any accidental breaking changes of a minor version update.


[[license]]
== ⚖️ License

.link:LICENSE[]
----
include::LICENSE[]
----
