---
# tasks file of ansible-role jonaspammer.goaccess

- name: check if all variables have been set correctly
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install GoAccess dependencies (including optional ones)
  ansible.builtin.package:
    name: "{{ goaccess_dependency_packages }}"
    state: present

- name: get current goaccess version # noqa risky-shell-pipe
  ansible.builtin.shell: >
    goaccess --version |
      head -n1 |
      grep --only "[0-9][.(0-9)]*" |
      head --bytes -2
  changed_when: false
  failed_when: false
  register: goaccess__register_command_goaccess_version_before

- name: Include Tasks for installing GoAccess by using the system package manager (when configured).
  ansible.builtin.include_tasks: "install-from_system.yml"
  when: goaccess_install_method in ["system"]

- name: Include Tasks for installing GoAccess from source (when configured).
  ansible.builtin.include_tasks: install-from_source.yml
  when: >
    goaccess_install_method in ["source"] and
    (
    goaccess__register_command_goaccess_version_before.rc != 0 or
    goaccess__register_command_goaccess_version_before.stdout != goaccess_version
    )

- name: Generate goaccess configuration file under configured path.
  ansible.builtin.template:
    src: goaccess.conf.jinja2
    dest: "{{ goaccess_conf_file_dir }}/.goaccess.conf"
    owner: "{{ goaccess_conf_file_owner }}"
    group: "{{ goaccess_conf_file_group }}"
    mode: "{{ goaccess_conf_file_mode }}"

- name: Ensure configured goaccess default log file has the defined properties and/or permissions.
  ansible.builtin.file:
    path: "{{ goaccess_conf_log_file }}"
    state: "{{ goaccess_conf_log_file__state | default(omit) }}"
    owner: "{{ goaccess_conf_log_file__owner | default(omit) }}"
    group: "{{ goaccess_conf_log_file__group | default(omit) }}"
    mode: "{{ goaccess_conf_log_file__mode | default(omit) }}"
  when: goaccess_conf_log_file is not None

- name: Generate GoAccess Systemd Unit File (when enabled).
  ansible.builtin.template:
    src: goaccess.service.jinja2
    dest: "/etc/systemd/system/{{ goaccess_systemd_name }}.service"
    owner: "{{ goaccess_conf_file_owner }}"
    group: "{{ goaccess_conf_file_group }}"
    mode: "{{ goaccess_conf_file_mode }}"
  when: goaccess_systemd

- name: Ensure GoAccess Systemd Unit is started and enabled on boot (when enabled).
  ansible.builtin.service:
    name: "{{ goaccess_systemd_name }}"
    state: started
    enabled: true
  when: goaccess_systemd
