---
- name: Converge
  hosts: all

  roles:
    - role: "ansible-role-goaccess"

- name: Converge GoAccess Systemd
  hosts: all

  vars:
    goaccess_systemd: true
    goaccess_conf_file: "/home/{{ goaccess_conf_file_owner }}/.goaccessrc"
    goaccess_conf_file_owner: myuser
    goaccess_conf_file_group: "{{ goaccess_conf_file_owner }}"
    goaccess_conf_log_file_group: "{{ goaccess_conf_file_group }}"
    goaccess_conf_log_dir_mode: u=rwx,g=r,o=

  pre_tasks:
    - name: create linux group
      ansible.builtin.group:
        name: "{{ goaccess_conf_file_group }}"
        state: present
    - name: create linux user
      ansible.builtin.user:
        name: "{{ goaccess_conf_file_owner }}"
        group: "{{ goaccess_conf_file_group }}"
        shell: /bin/bash # for sanity of debugging
        groups:
          - "{{ 'adm' if ansible_os_family == 'Debian' else 'root' }}" # for being able to read in /var/log/apache2

  roles:
    - role: "ansible-role-goaccess"
