---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  ansible-lint
driver:
  name: docker
platforms:
  # service-enabled Docker image by geerlingguy
  - name: instance-${TOX_ENVNAME}-${MOLECULE_DISTRO:-debian10}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    # https://molecule.readthedocs.io/en/latest/examples.html#sharing-across-scenarios
    prepare: ../resources/prepare.yml
  options:
    v: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
      stdout_callback: yaml
verifier:
  name: ansible
