---
- name: output some generally helpful debug information about the provisioned machine
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: debug output machine facts
      ansible.builtin.include_tasks: ../resources/debug.yml

### Actual Role Verification Tasks:
- name: Verify
  hosts: all

  tasks:
    - name: Check if 'goaccess --version' works
      ansible.builtin.command: goaccess --version
      changed_when: false

    # fixes 403 behaviour of RHEL's Apache
    - name: ensure index.html exists in Apache's DocumentRoot and is the same
      ansible.builtin.copy:
        dest: "/var/www/html/index.html"
        mode: u=rw,g=r,o=r
        content: |
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="UTF-8">
              <title>HTML 5 Boilerplate</title>
            </head>
            <body>
              <p> SOME TEXT HERE </p>
            </body>
          </html>

    - name: contact localhost to get a apache2 access.log going
      ansible.builtin.uri:
        url: "http://localhost"
      changed_when: false

    - name: stat real time html file
      ansible.builtin.stat:
        path: "/var/www/html/goaccess-myuser.html" # as per default
      register: goaccess__register_stat_real_time_html

    - name: Check if real time html file is not empty (should've been generated by systemd service)
      ansible.builtin.assert:
        that:
          - goaccess__register_stat_real_time_html.stat.size != 0
