---
name: create declared labels

"on":
  push:
    branches:
      - master
    paths:
      - ".github/workflows/issue-label-manager.yml"
      - ".github/labels.yml"

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labels:
    name: Invoke issue-label-manager action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: crazy-max/ghaction-github-labeler@f4f6b96e7e747b5416cd470f3cfecf26abaa811e # v4
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false # false -> delete labels that aren't in `yaml-file`
