---
name: create declared labels
permissions:
  issues: write
  pull-requests: write
"on":
  issues:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/issue-label-manager.yml"
      - ".github/labels.yml"

jobs:
  labels:
    name: Invoke issue-label-manager action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crazy-max/ghaction-github-labeler@v4
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false # false -> delete labels that aren't in `yaml-file`
